# Generated by Django 5.2.8 on 2025-12-01 23:41

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('10000.00000000'), max_digits=20)),
                ('available_balance', models.DecimalField(decimal_places=8, default=Decimal('10000.00000000'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mock Wallet',
                'verbose_name_plural': 'Mock Wallets',
                'db_table': 'mock_wallets',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy/Long'), ('sell', 'Sell/Short')], max_length=10)),
                ('order_type', models.CharField(choices=[('limit', 'Limit'), ('market', 'Market'), ('stop_limit', 'Stop Limit'), ('stop_market', 'Stop Market'), ('take_profit', 'Take Profit'), ('stop_loss', 'Stop Loss')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('leverage', models.PositiveSmallIntegerField(default=10)),
                ('margin_mode', models.CharField(choices=[('cross', 'Cross'), ('isolated', 'Isolated')], default='cross', max_length=10)),
                ('margin_used', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('average_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('commission', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('leverage', models.PositiveSmallIntegerField(default=10)),
                ('margin_mode', models.CharField(choices=[('cross', 'Cross'), ('isolated', 'Isolated')], default='cross', max_length=10)),
                ('margin', models.DecimalField(decimal_places=8, max_digits=20)),
                ('liquidation_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('commission_asset', models.CharField(default='USDT', max_length=10)),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-executed_at'],
            },
        ),
    ]
